- .babelrc
- Makefile
- bin/json-graphql-server.js
- package.json
- webpack.config.js
- yarn.lock
We temporarily ditch rollup to make the cli work
> [RFR] Make cli work

- README.md
Documentation-driven development: this README explains what the package *should* do.
To be merged when we're there!
> [WIP] Add README file

- package.json
- src/jsonGraphqlExpress.js
- yarn.lock
Not needed since makeExecutableSchema offers the same feature
> [RFR] Remove Error package

- README.md
- example/data.js
- src/introspection/DateType.js
- src/introspection/getFilterTypesFromData.js
- src/introspection/getTypeFromValues.js
- src/resolver/Query/all.js
- src/resolver/index.js
```graphql
{
allCommands(
filter: { date_lt: "2016-08-15T03:03:57.828Z" }
page: 1
perPage: 5
) {
id
date
}
}
```
Returns
```json
{
"data": {
"allCommands": [
{
"id": "12",
"date": "2015-09-04T18:26:13.620Z"
},
{
"id": "13",
"date": "2016-04-04T16:46:57.195Z"
},
{
"id": "14",
"date": "2015-08-31T17:28:47.268Z"
},
{
"id": "15",
"date": "2015-05-30T13:58:16.404Z"
},
{
"id": "16",
"date": "2016-04-03T20:34:47.638Z"
}
]
}
}
```
> [RFR] Add Date type

- package.json
- src/introspection/DateType.js
- src/introspection/getFilterTypesFromData.js
- src/introspection/getTypeFromValues.js
- src/introspection/getTypeFromValues.spec.js
- src/introspection/hasType.js
- src/resolver/index.js
- yarn.lock
> [RFR] Add JSON support

- src/jsonGraphqlExpress.js
- src/jsonGraphqlExpress.spec.js
- src/resolver/Entity/index.spec.js
- src/resolver/Mutation/create.js
- src/resolver/Mutation/create.spec.js
- src/resolver/Mutation/remove.js
- src/resolver/Mutation/remove.spec.js
- src/resolver/Mutation/update.js
- src/resolver/Mutation/update.spec.js
- src/resolver/Query/all.js
- src/resolver/Query/all.spec.js
- src/resolver/Query/single.js
- src/resolver/Query/single.spec.js
- src/schemaBuilder.js
- src/schemaBuilder.spec.js
> [RFR] Add unit tests for the server side

- Makefile
- bin/json-graphql-server.js
- package.json
- yarn.lock
> [RFR] Add support for CORS in CLI tool

- README.md
- bin/json-graphql-server.js
- example/index.html
- package.json
- src/client.js
- src/index.js
- src/node.js
- webpack.config.js
> [RFR] Fix webpack build

- src/introspection/getSchemaFromData.js
- src/resolver/Query/meta.js
It was a string but should have been a Filter type generated for each entity (rg PostFilter, UserFilter, etc.)
> [RFR] Fix meta queries filter parameter

- README.md
- bin/json-graphql-server.js
> Add CLI option for custom port number

- README.md
updated README in order to reflect the right import with `jsonGraphqlExpress`.
> fixed jsonGraphqlExpress import, see #44

- package.json
- yarn.lock
> [RFR] Upgrade dependencies

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Custom.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/pull_request_template.md
- README.md
and add some files for contributions
> [RFR] Update Readme file

- README.md
- src/client.js
- src/jsonGraphqlExpress.js
- src/node.js
- src/schemaBuilder.js
This would make it easier to run in a lambda environment, instead of using Express.
> Add support + docs for exporting the GraphQLSchema

- .prettierrc
- Makefile
- babel.config.js
- webpack.config.js
It is not possible to run make watch. It uses rollup instead of webpack.
> [RFR] Fix make watch

- README.md
- src/introspection/getSchemaFromData.js
- src/introspection/getSchemaFromData.spec.js
Changes the return type to the given type instead of a boolean.
#102
> Fix remove return type

- README.md
- src/introspection/getFilterTypesFromData.js
- src/resolver/Query/applyFilters.js
- src/resolver/Query/applyFilters.spec.js
Adds a NEQ filter to all types (excluding Boolean and Array types).
Adds corresponding tests.
No related issue.
> Add neq filter

- README.md
- src/introspection/getSchemaFromData.js
- src/resolver/Mutation/createMany.js
- src/resolver/Mutation/createMany.spec.js
- src/resolver/index.js
Adds a create many mutation type, and associated tests.
Closes #106
> Add create many

- README.md
Adds the link to the project running on StackBlitz, built per the provided example, so that users can run json-graph-server immediately and see it in action :)
> Provide a live demo of example to the readme

- README.md
- bin/json-graphql-server.js
> Add full name arguments
